import js from "@eslint/js"
import globals from "globals"
import reactHooks from "eslint-plugin-react-hooks"
import reactRefresh from "eslint-plugin-react-refresh"
import tseslint from "typescript-eslint"
import { defineConfig, globalIgnores } from "eslint/config"

export default defineConfig([
  globalIgnores(["dist", ".astro", "node_modules", "public"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // eslint-plugin-react-hooks v7 folds the React Compiler's rules into
      // `recommended`, and neither config ships without them. This project does
      // not run the compiler, so the three below reject patterns that are
      // correct uncompiled: lazily initialising a ref during render (the pattern
      // React's own docs show), and calling Date.now() inside event handlers
      // declared in the component body. rules-of-hooks and exhaustive-deps,
      // the ones that catch real bugs here, stay on.
      "react-hooks/refs": "off",
      "react-hooks/purity": "off",
      "react-hooks/preserve-manual-memoization": "off",
      // Fires on `navigator.mediaSession.metadata = …` inside an effect, which
      // is the only way that API is used. It stayed quiet until an async
      // function was added to the component and the compiler stopped bailing
      // out before reaching it. The effect itself never changed.
      "react-hooks/immutability": "off",
    },
  },
  {
    // The service worker runs off the main thread, so self, caches and clients
    // are its globals rather than window's.
    files: ["src/sw.ts"],
    languageOptions: {
      globals: globals.serviceworker,
    },
  },
  {
    // Generated by the shadcn CLI and kept diffable against the registry, so
    // the fixes for these belong upstream rather than here. Fast Refresh is a
    // dev-server concern, and use-mobile's mount-time setState is how the
    // registry syncs with a media query.
    files: ["src/components/ui/**", "src/hooks/**"],
    rules: {
      "react-refresh/only-export-components": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
])
